/**
 * generated by Xtext 2.32.0
 */
package fr.n7.gs1;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Application</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.gs1.Application#getTables <em>Tables</em>}</li>
 * </ul>
 *
 * @see fr.n7.gs1.Gs1Package#getApplication()
 * @model
 * @generated
 */
public interface Application extends EObject
{
  /**
   * Returns the value of the '<em><b>Tables</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.gs1.Table}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tables</em>' containment reference list.
   * @see fr.n7.gs1.Gs1Package#getApplication_Tables()
   * @model containment="true"
   * @generated
   */
  EList<Table> getTables();

} // Application
