/**
 * generated by Xtext 2.32.0
 */
package fr.n7.gs1;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Colonnesimple</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.n7.gs1.Gs1Package#getColonnesimple()
 * @model
 * @generated
 */
public interface Colonnesimple extends Colonne
{
} // Colonnesimple
