/**
 * generated by Xtext 2.32.0
 */
package fr.n7.gs1;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Colonne derivee</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.gs1.Colonne_derivee#getExpression <em>Expression</em>}</li>
 * </ul>
 *
 * @see fr.n7.gs1.Gs1Package#getColonne_derivee()
 * @model
 * @generated
 */
public interface Colonne_derivee extends Colonne
{
  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(Expression)
   * @see fr.n7.gs1.Gs1Package#getColonne_derivee_Expression()
   * @model containment="true"
   * @generated
   */
  Expression getExpression();

  /**
   * Sets the value of the '{@link fr.n7.gs1.Colonne_derivee#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(Expression value);

} // Colonne_derivee
