/**
 * generated by Xtext 2.32.0
 */
package fr.n7.gs1;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.gs1.Model#getApplications <em>Applications</em>}</li>
 * </ul>
 *
 * @see fr.n7.gs1.Gs1Package#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Applications</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.gs1.Application}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Applications</em>' containment reference list.
   * @see fr.n7.gs1.Gs1Package#getModel_Applications()
   * @model containment="true"
   * @generated
   */
  EList<Application> getApplications();

} // Model
