/**
 * generated by Xtext 2.32.0
 */
package fr.n7.gs1;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operateur</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.gs1.Operateur#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see fr.n7.gs1.Gs1Package#getOperateur()
 * @model
 * @generated
 */
public interface Operateur extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link fr.n7.gs1.Operations}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see fr.n7.gs1.Operations
   * @see #setType(Operations)
   * @see fr.n7.gs1.Gs1Package#getOperateur_Type()
   * @model
   * @generated
   */
  Operations getType();

  /**
   * Sets the value of the '{@link fr.n7.gs1.Operateur#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see fr.n7.gs1.Operations
   * @see #getType()
   * @generated
   */
  void setType(Operations value);

} // Operateur
