/**
 * generated by Xtext 2.32.0
 */
package fr.n7.gs1.impl;

import fr.n7.gs1.Colonnesimple;
import fr.n7.gs1.Gs1Package;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Colonnesimple</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ColonnesimpleImpl extends ColonneImpl implements Colonnesimple
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ColonnesimpleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Gs1Package.Literals.COLONNESIMPLE;
  }

} //ColonnesimpleImpl
