/*
 * generated by Xtext 2.32.0
 */
package fr.n7.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class Gs1UiModule extends AbstractGs1UiModule {

	public Gs1UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
