/*
 * generated by Xtext 2.32.0
 */
package fr.n7;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class Gs1StandaloneSetup extends Gs1StandaloneSetupGenerated {

	public static void doSetup() {
		new Gs1StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
