/*
 * generated by Xtext 2.32.0
 */
package fr.n7.ui.tests;

import com.google.inject.Injector;
import fr.n7.gs1.ui.internal.Gs1Activator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class Gs1UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Gs1Activator.getInstance().getInjector("fr.n7.Gs1");
	}

}
